#include <MsgBoxConstants.au3>
Run("C:\\SeleniumScripts\\AYQAAutomation\\AutoIT\\Web\\AYTestDataTransferWS.exe")
WinWaitActive("Test DataTransfer Web Service")
ControlClick("Test DataTransfer Web Service", "","[CLASS:WindowsForms10.BUTTON.app.0.378734a; INSTANCE:3]")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:2]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:2]", "https://qaexport.applyyourself.com/AYDataTransferWS.asmx")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:5]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:5]", "ayauto")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:6]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:6]", "419")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:9]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:9]", "109")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:8]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:8]", "jreddy")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:7]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:7]", "Aaaa111{!}")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:3]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:3]", "C:\Selenium")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("0")
ControlClick("Test DataTransfer Web Service", "","[CLASS:WindowsForms10.BUTTON.app.0.378734a; INSTANCE:7]")
WinWaitActive("AYTestDataTransferWS")
ControlClick("AYTestDataTransferWS", "","[CLASS:Button; INSTANCE:1]")
WinClose("Test DataTransfer Web Service")
    Local Const $sFilePath = "C:\\Selenium\\exp*.txt"
    Local $iFileExists = FileExists($sFilePath)
    ; Display a message of whether the file exists or not.
    If $iFileExists Then
        MsgBox($MB_SYSTEMMODAL, "", "The file exists." & @CRLF & "FileExist returned: " & $iFileExists,2)
    Else
        MsgBox($MB_SYSTEMMODAL, "", "The file doesn't exist." & @CRLF & "FileExist returned: " & $iFileExists)
    EndIf
    ; Delete the temporary file.
    FileDelete($sFilePath)