;#include <MsgBoxConstants.au3>

Run("C:\\Selenium\\Web\\AYDataTransferWS_TestTool\\AYTestDataTransferWS.exe")
WinWaitActive("Test DataTransfer Web Service")
;ControlSend("FileZilla", "", "[NAME:rbtnExport; INSTANCE:3]","ftp.hobsons.com")
ControlClick("Test DataTransfer Web Service", "","[CLASS:WindowsForms10.BUTTON.app.0.378734a; INSTANCE:2]")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:2]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:2]", "https://qaexport.applyyourself.com/AYDataTransferWS.asmx")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:5]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:5]", "ayauto")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:6]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:6]", "419")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:9]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:9]", "108")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:8]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:8]", "jreddy")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:7]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:7]", "Aaaa111{!}")
ControlFocus("Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:3]")
Send("^a")
ControlSend( "Test DataTransfer Web Service","","[CLASS:WindowsForms10.EDIT.app.0.378734a; INSTANCE:3]", "C:\Selenium\impData.txt")
ControlClick("Test DataTransfer Web Service", "","[CLASS:WindowsForms10.BUTTON.app.0.378734a; INSTANCE:7]")
WinWaitActive("AYTestDataTransferWS")
ControlClick("AYTestDataTransferWS", "","[CLASS:Button; INSTANCE:1]")
sleep(10000)
WinClose("Test DataTransfer Web Service")

