WinWait("File Download")
WinActivate("File Download")
$ggg = ControlGetText("File Download","","[CLASS:SysLink]")
ControlClick("File Download", "", "[CLASS:Button;ID:4427]")
WinWait("Save As")
WinActivate("Save As")
ControlSetText("Save As", "", "[CLASS:Edit;INSTANCE:1]", "C:\AY\AY_Source_File\Webcenter\ExportFiles\"&$ggg)
;ControlSetText("Save As", "", "[CLASS:Edit;INSTANCE:1]", "T:\EMT\Quality Assurance\Selenium Scripts\AY\AY\AYAutoIt\WebCenter\"&$ggg)
ControlClick("Save As", "", "[CLASS:Button;TEXT:&Save]")